# Generated by Django 2.2.5 on 2019-12-13 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='pasticipants',
            new_name='participants',
        ),
    ]
